spring:
  application:
    name: default-app

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3334/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8081

